### PR TITLE
Add custom data format for attachments

### PR DESCRIPTION
**Pull request by jeremyspiegel**
We currently set the drag format of text/uri-list to allow users to drag
attachments between Front windows. However, this makes it so that
when dragging attachments out of Front to some applications, the
attachment will be interpreted as the URL instead of being inserted as a
file (Word and Outlook for example). To work around this, we use a
custom drag format of x-front-attachment.

### CODE REVIEW

**Comment by jeremyspiegel** [comment]
@quentez @decafdennis @eramdam 

Not sure if this is the approach you would recommend, but it seems simpler than trying to add generic support for this. What do you think? I did find this react-dnd issue but there is no response for it — https://github.com/react-dnd/react-dnd/issues/1533.

**Comment by decafdennis** [comment]
Sgtm.

**Comment by jeremyspiegel** [comment]
It doesn't look like I have write access frontapp/react-dnd, which is why the branch is on my personal fork.

**Comment by eramdam** [comment]
@jeremyspiegel you should have write access to the repo now

**Review by eramdam — APPROVED** [review]
LGTM, I would wait for Q's review given that I am not very familiar with react-dnd's codebase

**Comment by jeremyspiegel** [comment]
Here is how it would be used: https://github.com/frontapp/front-client/pull/2533

**Comment by ravern** [comment]
Hey @jeremyspiegel, just came across this from the main `react-dnd` repo. Am curious, in this PR, you added a native type `x-front-attachment` for `react-dnd` to accept. But where do you set this `x-front-attachment` type on the `dataTransfer` in the first place?

Thanks for this PR, am also trying to support DnD into native apps and across browser windows in my app and this code helps.

**Comment by jeremyspiegel** [comment]
Hi @ravernkoh 👋I have an `onDragStart` handler for my drag source element that calls `event.dataTransfer.setData('x-front-attachment', data)`. Hope that helps!

**Pull request merged**
